'use strict';
// そよぎ式AACアプリ カード定義
// 構造（id/カテゴリ/絵文字）は全言語共通。ラベルは LBL[言語][id]。
// 絵文字はなるべく古いUnicode世代を選び、古い端末でも表示されるようにする。

const CATEGORIES = [
  { id: 'core',   e: '⭐' },
  { id: 'feel',   e: '😊' },
  { id: 'cond',   e: '🤕' },
  { id: 'body',   e: '🧍' },
  { id: 'food',   e: '🍚' },
  { id: 'life',   e: '🍀' },
  { id: 'want',   e: '🙋' },
  { id: 'people', e: '👥' },
  { id: 'place',  e: '🏠' },
  { id: 'time',   e: '⏰' },
  { id: 'saved',  e: '📌' },
  { id: 'mine',   e: '❤️' }
];

const CARDS = [
  // ⭐ よくつかう（コア語彙）
  { id: 'yes',     cat: 'core', e: '⭕' },
  { id: 'noans',   cat: 'core', e: '❌' },
  { id: 'dontknow',cat: 'core', e: '🤷' },
  { id: 'want',    cat: 'core', e: '🙏' },
  { id: 'no',      cat: 'core', e: '✋' },
  { id: 'more',    cat: 'core', e: '➕' },
  { id: 'bit',     cat: 'core', e: '🤏' },
  { id: 'very',    cat: 'core', e: '❗' },
  { id: 'done',    cat: 'core', e: '✅' },
  { id: 'help',    cat: 'core', e: '🆘' },
  { id: 'wait',    cat: 'core', e: '⏳' },
  { id: 'look',    cat: 'core', e: '👀' },
  { id: 'come',    cat: 'core', e: '🤙' },
  { id: 'go',      cat: 'core', e: '🚶' },
  { id: 'this',    cat: 'core', e: '👆' },
  { id: 'notthis', cat: 'core', e: '🚫' },
  { id: 'what',    cat: 'core', e: '❓' },
  { id: 'where',   cat: 'core', e: '🔍' },
  { id: 'who',     cat: 'core', e: '👤❓' },
  { id: 'when',    cat: 'core', e: '🕐❓' },
  { id: 'ok',      cat: 'core', e: '👌' },
  { id: 'thanks',  cat: 'core', e: '💖' },
  { id: 'sorry',   cat: 'core', e: '🙇' },
  { id: 'please',  cat: 'core', e: '🙏✨' },
  // 😊 きもち
  { id: 'happy',       cat: 'feel', e: '😊' },
  { id: 'sad',         cat: 'feel', e: '😢' },
  { id: 'angry',       cat: 'feel', e: '😠' },
  { id: 'scared',      cat: 'feel', e: '😨' },
  { id: 'tired',       cat: 'feel', e: '😩' },
  { id: 'sleepy',      cat: 'feel', e: '😪' },
  { id: 'lonely',      cat: 'feel', e: '🥺' },
  { id: 'worried',     cat: 'feel', e: '😟' },
  { id: 'surprised',   cat: 'feel', e: '😲' },
  { id: 'fun',         cat: 'feel', e: '😄' },
  { id: 'frustrated',  cat: 'feel', e: '😤' },
  { id: 'embarrassed', cat: 'feel', e: '😳' },
  { id: 'calm',        cat: 'feel', e: '🧘' },
  { id: 'cry',         cat: 'feel', e: '😭' },
  { id: 'fine',        cat: 'feel', e: '🙆' },
  { id: 'like',        cat: 'feel', e: '❤️' },
  { id: 'hate',        cat: 'feel', e: '👎' },
  { id: 'badmouth',    cat: 'feel', e: '🗯️' },
  { id: 'bullied',     cat: 'feel', e: '💔' },
  { id: 'hit',         cat: 'feel', e: '👊' },
  { id: 'pinched',     cat: 'feel', e: '🤏💢' },
  { id: 'ignored',     cat: 'feel', e: '🙉' },
  { id: 'touched',     cat: 'feel', e: '✋💢' },
  { id: 'taken',       cat: 'feel', e: '💸' },
  { id: 'notgiven',    cat: 'feel', e: '🤲❌' },
  // 🤕 ぐあい（症状・できごと）
  { id: 'pain',      cat: 'cond', e: '💥' },
  { id: 'itchy',     cat: 'cond', e: '😖' },
  { id: 'fever',     cat: 'cond', e: '🌡️' },
  { id: 'nausea',    cat: 'cond', e: '🤢' },
  { id: 'dizzy',     cat: 'cond', e: '💫' },
  { id: 'hard',      cat: 'cond', e: '😣' },
  { id: 'cough',     cat: 'cond', e: '😷' },
  { id: 'sleepless', cat: 'cond', e: '🛌' },
  { id: 'numb',      cat: 'cond', e: '⚡' },
  { id: 'sluggish',  cat: 'cond', e: '🥱' },
  { id: 'bleeding',  cat: 'cond', e: '🩸' },
  { id: 'swollen',   cat: 'cond', e: '🐡' },
  { id: 'shiver',    cat: 'cond', e: '〰️' },
  { id: 'chills',    cat: 'cond', e: '🧊' },
  { id: 'racing',    cat: 'cond', e: '💗' },
  { id: 'breathless',cat: 'cond', e: '💨' },
  { id: 'constip',   cat: 'cond', e: '🚽' },
  { id: 'diarrhea',  cat: 'cond', e: '💩' },
  { id: 'choke',     cat: 'cond', e: '🍚💦' },
  { id: 'period',    cat: 'cond', e: '🌸' },
  { id: 'fell',      cat: 'cond', e: '⚠️' },
  { id: 'bumped',    cat: 'cond', e: '💢' },
  { id: 'burned',    cat: 'cond', e: '🔥' },
  { id: 'leaked',    cat: 'cond', e: '💦' },
  { id: 'cantsee',   cat: 'cond', e: '👓' },
  { id: 'canthear',  cat: 'cond', e: '🦻' },
  // 🧍 からだ（部位・あたまから つまさきへ）
  { id: 'head',      cat: 'body', e: '🧠' },
  { id: 'eye',       cat: 'body', e: '👁️' },
  { id: 'ear',       cat: 'body', e: '👂' },
  { id: 'nose',      cat: 'body', e: '👃' },
  { id: 'mouth',     cat: 'body', e: '👄' },
  { id: 'tooth',     cat: 'body', e: '🦷' },
  { id: 'throat',    cat: 'body', e: '🗣️' },
  { id: 'neck',      cat: 'body', e: '🧣' },
  { id: 'shoulder',  cat: 'body', e: '💆' },
  { id: 'chest',     cat: 'body', e: '💓' },
  { id: 'belly',     cat: 'body', e: '🌀' },
  { id: 'upperback', cat: 'body', e: '🎒' },
  { id: 'back',      cat: 'body', e: '🦴' },
  { id: 'hip',       cat: 'body', e: '🍑' },
  { id: 'arm',       cat: 'body', e: '💪' },
  { id: 'hand',      cat: 'body', e: '🤚' },
  { id: 'finger',    cat: 'body', e: '☝️' },
  { id: 'leg',       cat: 'body', e: '🦵' },
  { id: 'knee',      cat: 'body', e: '🧎' },
  { id: 'skin',      cat: 'body', e: '🧴' },
  // 🍚 たべる・のむ
  { id: 'eat',     cat: 'food', e: '🍽️' },
  { id: 'drink',   cat: 'food', e: '🥤' },
  { id: 'water',   cat: 'food', e: '💧' },
  { id: 'tea',     cat: 'food', e: '🍵' },
  { id: 'juice',   cat: 'food', e: '🧃' },
  { id: 'milk',    cat: 'food', e: '🥛' },
  { id: 'rice',    cat: 'food', e: '🍚' },
  { id: 'bread',   cat: 'food', e: '🍞' },
  { id: 'noodle',  cat: 'food', e: '🍜' },
  { id: 'snack',   cat: 'food', e: '🍪' },
  { id: 'fruit',   cat: 'food', e: '🍎' },
  { id: 'veggie',  cat: 'food', e: '🥕' },
  { id: 'yum',     cat: 'food', e: '😋' },
  { id: 'dislike', cat: 'food', e: '😝' },
  { id: 'nomore',  cat: 'food', e: '🙅' },
  // 🍀 せいかつ
  { id: 'toilet',   cat: 'life', e: '🚻' },
  { id: 'bath',     cat: 'life', e: '🛁' },
  { id: 'sleep',    cat: 'life', e: '🛏️' },
  { id: 'wake',     cat: 'life', e: '☀️' },
  { id: 'clothes',  cat: 'life', e: '👕' },
  { id: 'medicine', cat: 'life', e: '💊' },
  { id: 'brush',    cat: 'life', e: '🦷✨' },
  { id: 'tv',       cat: 'life', e: '📺' },
  { id: 'music',    cat: 'life', e: '🎵' },
  { id: 'game',     cat: 'life', e: '🎮' },
  { id: 'book',     cat: 'life', e: '📖' },
  { id: 'outside',  cat: 'life', e: '🌳' },
  { id: 'walk',     cat: 'life', e: '🚶‍♀️' },
  { id: 'hot',      cat: 'life', e: '🥵' },
  { id: 'cold',     cat: 'life', e: '🥶' },
  { id: 'light',    cat: 'life', e: '💡' },
  { id: 'money',    cat: 'life', e: '💰' },
  // 🙋 したいこと
  { id: 'stay',     cat: 'want', e: '🤲' },
  { id: 'homewant', cat: 'want', e: '🏡' },
  { id: 'rest',     cat: 'want', e: '🛋️' },
  { id: 'play',     cat: 'want', e: '🎈' },
  { id: 'watch',    cat: 'want', e: '🎬' },
  { id: 'listen',   cat: 'want', e: '🎧' },
  { id: 'dowant',   cat: 'want', e: '💪' },
  { id: 'stopwant', cat: 'want', e: '🛑' },
  { id: 'alone',    cat: 'want', e: '🚪' },
  { id: 'hug',      cat: 'want', e: '🤗' },
  { id: 'helpme',   cat: 'want', e: '🤝' },
  { id: 'tellme',   cat: 'want', e: '🗨️' },
  { id: 'phone',    cat: 'want', e: '📞' },
  { id: 'shopping', cat: 'want', e: '🛒' },
  // 👥 ひと
  { id: 'me',       cat: 'people', e: '🙋' },
  { id: 'you',      cat: 'people', e: '🧍' },
  { id: 'mom',      cat: 'people', e: '👩' },
  { id: 'dad',      cat: 'people', e: '👨' },
  { id: 'husband',  cat: 'people', e: '🤵' },
  { id: 'wife',     cat: 'people', e: '👰' },
  { id: 'son',      cat: 'people', e: '👦' },
  { id: 'daughter', cat: 'people', e: '👧' },
  { id: 'sibling',  cat: 'people', e: '🧒' },
  { id: 'grandpa',  cat: 'people', e: '👴' },
  { id: 'grandma',  cat: 'people', e: '👵' },
  { id: 'baby',     cat: 'people', e: '👶' },
  { id: 'family',   cat: 'people', e: '👨‍👩‍👧' },
  { id: 'pet',      cat: 'people', e: '🐶' },
  { id: 'friend',   cat: 'people', e: '👫' },
  { id: 'teacher',  cat: 'people', e: '👩‍🏫' },
  { id: 'doctor',   cat: 'people', e: '👨‍⚕️' },
  { id: 'nurse',    cat: 'people', e: '👩‍⚕️' },
  { id: 'helper',     cat: 'people', e: '💁' },
  { id: 'careworker', cat: 'people', e: '🤲' },
  { id: 'supworker',  cat: 'people', e: '🧑‍🤝‍🧑' },
  { id: 'caremgr',  cat: 'people', e: '📋' },
  { id: 'therapist',cat: 'people', e: '🏋️' },
  { id: 'staff',    cat: 'people', e: '👔' },
  { id: 'driver',   cat: 'people', e: '🚕' },
  { id: 'stranger', cat: 'people', e: '👤' },
  { id: 'everyone', cat: 'people', e: '👥' },
  // 🏠 ばしょ
  { id: 'home',     cat: 'place', e: '🏠' },
  { id: 'school',   cat: 'place', e: '🏫' },
  { id: 'hospital', cat: 'place', e: '🏥' },
  { id: 'store',    cat: 'place', e: '🏪' },
  { id: 'park',     cat: 'place', e: '⛲' },
  { id: 'station',  cat: 'place', e: '🚉' },
  { id: 'train',    cat: 'place', e: '🚃' },
  { id: 'car',      cat: 'place', e: '🚗' },
  { id: 'bus',      cat: 'place', e: '🚌' },
  { id: 'work',     cat: 'place', e: '🏢' },
  { id: 'police',   cat: 'place', e: '👮' },
  { id: 'out',      cat: 'place', e: '🌳' },
  // ⏰ じかん
  { id: 'now',       cat: 'time', e: '⏱️' },
  { id: 'today',     cat: 'time', e: '📅' },
  { id: 'tomorrow',  cat: 'time', e: '🌅' },
  { id: 'yesterday', cat: 'time', e: '🌙' },
  { id: 'morning',   cat: 'time', e: '🐓' },
  { id: 'daytime',   cat: 'time', e: '🌤️' },
  { id: 'night',     cat: 'time', e: '🌃' },
  { id: 'later',     cat: 'time', e: '⌛' },
  { id: 'notyet',    cat: 'time', e: '🐢' },
  { id: 'already',   cat: 'time', e: '🏁' },
  { id: 'before',    cat: 'time', e: '⏪' },
  { id: 'after',     cat: 'time', e: '⏩' },
  // 数字+単位で「3時」「10分」「1時間」を組める
  { id: 'n1',        cat: 'time', e: '1' },
  { id: 'n3',        cat: 'time', e: '3' },
  { id: 'n5',        cat: 'time', e: '5' },
  { id: 'n10',       cat: 'time', e: '10' },
  { id: 'n15',       cat: 'time', e: '15' },
  { id: 'n30',       cat: 'time', e: '30' },
  { id: 'n45',       cat: 'time', e: '45' },
  { id: 'n60',       cat: 'time', e: '60' },
  { id: 'min',       cat: 'time', e: '⏲️' },
  { id: 'oclock',    cat: 'time', e: '🕒' },
  { id: 'hourdur',   cat: 'time', e: '🕰️' }
];

// 🚨 きんきゅう（文まるごと・タップで即よみあげ）
const ER_CARDS = [
  { id: 'erhelp',      e: '🆘' },
  { id: 'erambulance', e: '🚑' },
  { id: 'erpain',      e: '💥' },
  { id: 'erbreath',    e: '😵' },
  { id: 'ertoilet',    e: '🚻' },
  { id: 'erwater',     e: '💧' },
  { id: 'erscared',    e: '🏃' },
  { id: 'erpolice',    e: '🚓' }
];

const LBL = {
  ja: {
    yes: 'はい', noans: 'いいえ', dontknow: 'わからない',
    want: 'ほしい', no: 'いや', more: 'もっと', bit: 'すこし', very: 'とても',
    done: 'おわり', help: 'たすけて',
    wait: 'まって', look: 'みて', come: 'きて', go: 'いく', this: 'これ',
    notthis: 'ちがう', what: 'なに？', where: 'どこ？', who: 'だれ？',
    when: 'いつ？', ok: 'いいよ',
    thanks: 'ありがとう', sorry: 'ごめんなさい', please: 'おねがいします',
    happy: 'うれしい', sad: 'かなしい', angry: 'おこってる', scared: 'こわい',
    tired: 'つかれた', sleepy: 'ねむい', lonely: 'さびしい', worried: 'しんぱい',
    surprised: 'びっくりした', fun: 'たのしい', frustrated: 'いらいらする',
    embarrassed: 'はずかしい', calm: 'おちつきたい', cry: 'なきたい',
    fine: 'だいじょうぶ', like: 'すき', hate: 'きらい',
    badmouth: 'わるぐちを いわれた', bullied: 'いじめられた', hit: 'たたかれた',
    pinched: 'つねられた', ignored: 'むしされた',
    touched: 'さわられた', taken: 'とられた', notgiven: 'もらえなかった',
    pain: 'いたい', itchy: 'かゆい', fever: 'ねつがある', nausea: 'きもちわるい',
    dizzy: 'めまいがする', hard: 'くるしい', cough: 'せきがでる', sleepless: 'ねむれない',
    numb: 'しびれる', sluggish: 'だるい', bleeding: 'ちがでた', swollen: 'はれてる',
    shiver: 'ふるえる', chills: 'さむけがする', racing: 'ドキドキする',
    breathless: 'いきがきれる', constip: 'べんぴ', diarrhea: 'げり',
    choke: 'むせる', period: 'せいり', fell: 'ころんだ', bumped: 'ぶつけた',
    burned: 'やけどした', leaked: 'もれちゃった', cantsee: 'みえにくい',
    canthear: 'きこえにくい',
    head: 'あたま', eye: 'め', ear: 'みみ', nose: 'はな', mouth: 'くち',
    tooth: 'は', throat: 'のど', neck: 'くび', shoulder: 'かた',
    chest: 'むね', belly: 'おなか', upperback: 'せなか', back: 'こし',
    hip: 'おしり', arm: 'うで', hand: 'て', finger: 'ゆび', leg: 'あし',
    knee: 'ひざ', skin: 'はだ',
    eat: 'たべたい', drink: 'のみたい', water: 'みず', tea: 'おちゃ',
    juice: 'ジュース', milk: 'ぎゅうにゅう', rice: 'ごはん', bread: 'パン',
    noodle: 'めん', snack: 'おかし', fruit: 'くだもの', veggie: 'やさい',
    yum: 'おいしい',
    dislike: 'すきじゃない', nomore: 'もういらない',
    toilet: 'トイレ', bath: 'おふろ', sleep: 'ねる', wake: 'おきる',
    clothes: 'きがえたい', medicine: 'くすり', brush: 'はみがき', tv: 'テレビ',
    music: 'おんがく', game: 'ゲーム', book: 'ほん', outside: 'そとにでたい',
    walk: 'さんぽ', hot: 'あつい', cold: 'さむい', light: 'でんき',
    money: 'おかね',
    stay: 'そばにいて', homewant: 'かえりたい', rest: 'やすみたい', play: 'あそびたい',
    watch: 'みたい', listen: 'ききたい', dowant: 'やりたい', stopwant: 'やめたい',
    alone: 'ひとりになりたい', hug: 'ぎゅっとして', helpme: 'てつだって',
    tellme: 'おしえて', phone: 'でんわしたい', shopping: 'かいものしたい',
    me: 'わたし', you: 'あなた', mom: 'おかあさん', dad: 'おとうさん',
    husband: 'おっと', wife: 'つま', son: 'むすこ', daughter: 'むすめ',
    sibling: 'きょうだい', grandpa: 'おじいちゃん', grandma: 'おばあちゃん',
    baby: 'あかちゃん', family: 'かぞく', pet: 'ペット', friend: 'ともだち',
    teacher: 'せんせい', doctor: 'おいしゃさん', nurse: 'かんごしさん',
    helper: 'ヘルパーさん', careworker: 'かいごしさん', supworker: 'しえんいんさん',
    caremgr: 'ケアマネさん', therapist: 'リハビリのせんせい',
    staff: 'スタッフさん', driver: 'うんてんしゅさん', stranger: 'しらないひと',
    everyone: 'みんな',
    home: 'いえ', school: 'がっこう', hospital: 'びょういん', store: 'おみせ',
    park: 'こうえん', station: 'えき', train: 'でんしゃ', car: 'くるま',
    bus: 'バス', work: 'しごと', police: 'こうばん', out: 'そと',
    now: 'いま', today: 'きょう', tomorrow: 'あした', yesterday: 'きのう',
    morning: 'あさ', daytime: 'ひる', night: 'よる', later: 'あとで',
    notyet: 'まだ', already: 'もう', before: 'まえ', after: 'あと',
    n1: '1', n3: '3', n5: '5', n10: '10', n15: '15', n30: '30', n45: '45', n60: '60',
    min: 'ふん', oclock: 'じ', hourdur: 'じかん',
    erhelp: 'たすけてください', erambulance: 'きゅうきゅうしゃを よんでください',
    erpain: 'すごく いたいです', erbreath: 'いきが くるしいです',
    ertoilet: 'トイレに いきたいです', erwater: 'みずを ください',
    erscared: 'こわいです。にげたいです', erpolice: 'けいさつを よんでください'
  },
  en: {
    yes: 'yes', noans: 'no', dontknow: "I don't know",
    want: 'I want', no: "I don't want", more: 'more', bit: 'a little', very: 'very',
    done: 'finished', help: 'help',
    wait: 'wait', look: 'look', come: 'come here', go: 'go', this: 'this',
    notthis: 'not this', what: 'what?', where: 'where?', who: 'who?',
    when: 'when?', ok: 'OK',
    thanks: 'thank you', sorry: 'sorry', please: 'please',
    happy: 'happy', sad: 'sad', angry: 'angry', scared: 'scared',
    tired: 'tired', sleepy: 'sleepy', lonely: 'lonely', worried: 'worried',
    surprised: 'surprised', fun: 'having fun', frustrated: 'frustrated',
    embarrassed: 'embarrassed', calm: 'I want to calm down', cry: 'I want to cry',
    fine: "I'm okay", like: 'I like it', hate: "I hate it",
    badmouth: 'someone said mean things', bullied: "I'm being bullied",
    hit: 'someone hit me', pinched: 'someone pinched me',
    ignored: "I'm being ignored",
    touched: 'someone touched me', taken: 'someone took it',
    notgiven: "I didn't get it",
    pain: 'it hurts', itchy: 'itchy', fever: 'I have a fever', nausea: 'I feel sick',
    dizzy: 'dizzy', hard: 'I feel awful', cough: 'coughing', sleepless: "can't sleep",
    numb: 'numb', sluggish: 'no energy', bleeding: 'bleeding', swollen: 'swollen',
    shiver: 'shivering', chills: 'chills', racing: 'my heart is racing',
    breathless: 'short of breath', constip: 'constipated', diarrhea: 'diarrhea',
    choke: 'choking when eating', period: 'my period', fell: 'I fell down',
    bumped: 'I bumped it', burned: 'I got burned', leaked: 'I had an accident',
    cantsee: "can't see well", canthear: "can't hear well",
    head: 'head', eye: 'eye', ear: 'ear', nose: 'nose', mouth: 'mouth',
    tooth: 'tooth', throat: 'throat', neck: 'neck', shoulder: 'shoulder',
    chest: 'chest', belly: 'stomach', upperback: 'back', back: 'lower back',
    hip: 'bottom', arm: 'arm', hand: 'hand', finger: 'finger', leg: 'leg',
    knee: 'knee', skin: 'skin',
    eat: 'I want to eat', drink: 'I want to drink', water: 'water', tea: 'tea',
    juice: 'juice', milk: 'milk', rice: 'rice', bread: 'bread',
    noodle: 'noodles', snack: 'a snack', fruit: 'fruit', veggie: 'vegetables',
    yum: 'yummy',
    dislike: "I don't like it", nomore: 'no more',
    toilet: 'toilet', bath: 'bath', sleep: 'sleep', wake: 'wake up',
    clothes: 'change clothes', medicine: 'medicine', brush: 'brush teeth', tv: 'TV',
    music: 'music', game: 'games', book: 'a book', outside: 'go outside',
    walk: 'a walk', hot: 'hot', cold: 'cold', light: 'the light',
    money: 'money',
    stay: 'stay with me', homewant: 'I want to go home', rest: 'I want to rest',
    play: 'I want to play', watch: 'I want to watch', listen: 'I want to listen',
    dowant: 'I want to do it', stopwant: 'I want to stop',
    alone: 'I want to be alone', hug: 'hug me', helpme: 'help me please',
    tellme: 'tell me', phone: 'I want to call', shopping: 'I want to go shopping',
    me: 'me', you: 'you', mom: 'Mom', dad: 'Dad',
    husband: 'my husband', wife: 'my wife', son: 'my son', daughter: 'my daughter',
    sibling: 'my sibling', grandpa: 'Grandpa', grandma: 'Grandma',
    baby: 'the baby', family: 'family', pet: 'my pet', friend: 'my friend',
    teacher: 'teacher', doctor: 'doctor', nurse: 'nurse',
    helper: 'home helper', careworker: 'care worker', supworker: 'support worker',
    caremgr: 'care manager', therapist: 'therapist',
    staff: 'staff', driver: 'the driver', stranger: 'a stranger',
    everyone: 'everyone',
    home: 'home', school: 'school', hospital: 'hospital', store: 'store',
    park: 'park', station: 'station', train: 'train', car: 'car',
    bus: 'bus', work: 'work', police: 'police', out: 'outside',
    now: 'now', today: 'today', tomorrow: 'tomorrow', yesterday: 'yesterday',
    morning: 'morning', daytime: 'daytime', night: 'night', later: 'later',
    notyet: 'not yet', already: 'already', before: 'before', after: 'after',
    n1: '1', n3: '3', n5: '5', n10: '10', n15: '15', n30: '30', n45: '45', n60: '60',
    min: 'minutes', oclock: "o'clock", hourdur: 'hours',
    erhelp: 'Please help me!', erambulance: 'Call an ambulance!',
    erpain: "It hurts so much!", erbreath: "I can't breathe!",
    ertoilet: 'I need the toilet now!', erwater: 'Water, please!',
    erscared: "I'm scared. I want to leave!", erpolice: 'Call the police!'
  }
};
